defaults: []

run: null  # pass via CLI
run_id: null  # set from run-specific config
results_dir: ./results
mode: full  # trial or full

wandb:
  entity: gengaru617-personal
  project: 2026-01-22-2
  mode: online  # updated depending on mode at runtime
